### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by tom-dalton-fanduel** [devinatfanduel/devbot_testing#1]
Could you fix these up so there's only one version in the repo?

`/devbotapp.py` & `/devbotapp2.py`
`/templates/comp_upload.html` & `/templates/comp_upload2.html`
`/templates/index.html` & `/templates/index2.html`

**Comment by devinatfanduel** [comment]
The comp_upload ones are actually different pages. Could be named better probably. Removed the other dupe files.
